version: 0.2
            
phases:
  pre_build:
    commands:
      - cd $CODEBUILD_SRC_DIR/thermostat-service/timeseries
      - npm install
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR/thermostat-service/timeseries
      - npm run test
      - cd $CODEBUILD_SRC_DIR
      - /bin/bash ./package.sh
      - /bin/bash ./deploy.sh
    finally:
artifacts:
  files:
    - packaged.yaml
  discard-paths: yes
  base-directory: location
cache:
  paths:
    - thermostat-service/timeseries/node_modules