AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    thermostat-service

    Sample SAM Template for thermostat-service
    
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 3


Resources:

    TimeseriesFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: timeseries/
            Handler: app.lambdaHandler
            Runtime: nodejs8.10
            Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
                Variables:
                    PARAM1: VALUE
            Events:
                GetTimeseriesApi:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /timeseries
                        Method: get
                PostTimeseriesApi:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /timeseries
                        Method: post

Outputs:

    TimeseriesApi:
      Description: "API Gateway endpoint URL for Prod stage for Timeseries function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/timeseries/"

    TimeseriesFunction:
      Description: "Timeseries Lambda Function ARN"
      Value: !GetAtt TimeseriesFunction.Arn

    TimeseriesFunctionIamRole:
      Description: "Implicit IAM Role created for Timeseries function"
      Value: !GetAtt TimeseriesFunctionRole.Arn
